drop table car;
CREATE TABLE car (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR2(50) NOT NULL,
    model VARCHAR2(50) NOT NULL,
    year NUMBER NOT NULL,
    engine_capacity NUMBER(3,1) NOT NULL
);

INSERT INTO car (manufacturer, model, year, engine_capacity) VALUES ('Toyota', 'Corolla', 2010, 1.8);
INSERT INTO car (manufacturer, model, year, engine_capacity) VALUES ('Audi', 'A4', 2015, 2.0);
INSERT INTO car (manufacturer, model, year, engine_capacity) VALUES ('Honda', 'Civic', 2012, 1.6);
INSERT INTO car (manufacturer, model, year, engine_capacity) VALUES ('BMW', 'X5', 2018, 3.0);
INSERT INTO car (manufacturer, model, year, engine_capacity) VALUES ('Ford', 'Fiesta', 2017, 1.5);

select * from car;
